User.create!(:email => 'toughjjh@gmail.com',:name=>'잠자는-사자',:password => 'jjh123456', :password_confirmation => 'jjh123456',:admin=>true)     

GalleryCategory.create!(:user_id=>1,:title=>'미용실전경')
GalleryCategory.create!(:user_id=>1,:title=>'미용')

ProductCategory.create!(:id=>1,:title=>'상품분류1')
ProductCategory.create!(:id=>2,:title=>'상품분류2')
ProductCategory.create!(:id=>3,:title=>'상품분류3')
ProductCategory.create!(:id=>4,:title=>'상품분류4')
ProductCategory.create!(:id=>5,:title=>'상품분류5')
ProductCategory.create!(:id=>6,:title=>'상품분류6')
ProductCategory.create!(:id=>7,:title=>'상품분류7')
ProductCategory.create!(:id=>8,:title=>'상품분류8')


FaqCategory.create!(:title=>'이용안내')
FaqCategory.create!(:title=>'기타')
Faq.create!(:faq_category_id=>1,:id=>1,:title=>'11111')
Faq.create!(:faq_category_id=>1,:id=>2,:title=>'22222')
Faq.create!(:faq_category_id=>1,:id=>3,:title=>'33333')     
Faq.create!(:faq_category_id=>2,:id=>4,:title=>'44444')
FaqContent.create!(:id=>1,:content=>'11111')
FaqContent.create!(:id=>2,:content=>'22222')
FaqContent.create!(:id=>3,:content=>'33333')    
FaqContent.create!(:id=>4,:content=>'44444')

Resource.create!(:id=>1,:ad_position_id=>3,:title=>'메인',:menu_display=>false,:controller=>'home',:description=>'처음화면',:priority=>9000)
Resource.create!(:id=>2,:ad_position_id=>3,:title=>'소개',:menu_display=>true,:controller=>'intro',:description=>'소개',:priority=>1000)
Resource.create!(:id=>3,:ad_position_id=>2,:title=>'갤러리',:menu_display=>true,:controller=>'galleries',:use_category=>true,:description=>'갤러리',:priority=>2000)
Resource.create!(:id=>4,:ad_position_id=>2,:title=>'블로그',:menu_display=>true,:controller=>'blogs',:use_category=>true,:description=>'블로그',:priority=>3000)
Resource.create!(:id=>5,:ad_position_id=>2,:title=>'질문, 답변',:menu_display=>true,:controller=>'questions',:description=>'질문,답변',:priority=>4000)
Resource.create!(:id=>6,:ad_position_id=>2,:title=>'FAQ',:menu_display=>true,:controller=>'faqs',:use_category=>true,:description=>'FAQ',:priority=>5000)
Resource.create!(:id=>7,:ad_position_id=>2,:title=>'상담,문의',:menu_display=>false,:controller=>'contacts',:menu_action=>'new',:description=>'상담 문의를 받을수 있게 합니다.',:priority=>6000)
Resource.create!(:id=>8,:ad_position_id=>2,:title=>'공지사항',:menu_display=>false,:controller=>'notices',:description=>'운영자가 방문자들에게 알릴 공지사항을 알릴수 있게 합니다.',:priority=>7000)
Resource.create!(:id=>9,:ad_position_id=>2,:title=>'방명록',:menu_display=>true,:controller=>'guest_books',:description=>'방문자가 글을 쓸수 있는 방명록입니다.',:priority=>8000)
Resource.create!(:id=>10,:ad_position_id=>2,:title=>'연혁',:menu_display=>false,:controller=>'histories',:description=>'연혁',:priority=>8000)
Resource.create!(:id=>11,:ad_position_id=>2,:title=>'포트폴리오',:menu_display=>false,:controller=>'portfolios',:description=>'포트폴리오',:priority=>8000)
Resource.create!(:id=>12,:ad_position_id=>2,:title=>'회원가입',:menu_display=>false,:controller=>'users',:menu_action=>'new',:description=>'사용자',:priority=>9000)
Resource.create!(:id=>13,:ad_position_id=>2,:title=>'사이트',:menu_display=>false,:controller=>'site',:menu_action=>'new',:description=>'사이트 소개',:priority=>9000)
Resource.create!(:id=>14,:ad_position_id=>2,:title=>'제품',:menu_display=>true,:controller=>'products',:description=>'제품 소개',:priority=>9000)

